### ISSUE TITLE
Link for slime spec not working

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [Geek202/slime-for-fabric#1]
Heya, I've noticed that the link that goes to the slime modified spec is invalid? It still points to the user `geek202`, but changing it to `Tom-The-Geek` manually works, so maybe update it? :P

Also is there any chance of this being developed for 1.18.2?

**Comment by Tom-The-Geek** [comment]
Unfortunately I have no plans to update this to newer versions, as the format really isn't designed very well, and I would not even recommend using it anyway, as it was mostly an experiment, and not really suited to production use. Sorry
